### ISSUE TITLE
Couldn't resolve parser

### ISSUE THREAD

**Issue by Wolfr** [roxiness/stackmix#23]
Just posting some output here I got when setting up a new project using Stackmix which is not that clean.

Node 14.15.0

Could this be because I don't have prettier installed globally?

```
npx stackmix boekentorenroutify
npx: installed 130 in 5.645s
✔ Pick a bundler. Combine at your own risk. › vite
✔ Pick a template. Combine at your own risk. › scroll-navigation
✔ Pick features. › markdown, milligram, postcss, vercel
✔ Pick content. › content
✔ Misc › dev
ConfigError: Couldn't resolve parser "babel-ts"
    at resolveParser$1 (/usr/local/lib/node_modules/prettier/bin-prettier.js:6974:13)
    at normalize (/usr/local/lib/node_modules/prettier/bin-prettier.js:7065:19)
    at textToDoc (/usr/local/lib/node_modules/prettier/bin-prettier.js:9830:21)
    at /usr/local/lib/node_modules/prettier/bin-prettier.js:9824:14
    at formatBodyContent (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1675:22)
    at /Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:85
    at embedTag (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1697:15)
    at embedType (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:52)
    at embedScript (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1623:41)
    at Object.embed (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1632:20)
ConfigError: Couldn't resolve parser "babel-ts"
    at resolveParser$1 (/usr/local/lib/node_modules/prettier/bin-prettier.js:6974:13)
    at normalize (/usr/local/lib/node_modules/prettier/bin-prettier.js:7065:19)
    at textToDoc (/usr/local/lib/node_modules/prettier/bin-prettier.js:9830:21)
    at /usr/local/lib/node_modules/prettier/bin-prettier.js:9824:14
    at formatBodyContent (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1675:22)
    at /Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:85
    at embedTag (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1697:15)
    at embedType (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:52)
    at embedScript (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1623:41)
    at Object.embed (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1632:20)
ConfigError: Couldn't resolve parser "babel-ts"
    at resolveParser$1 (/usr/local/lib/node_modules/prettier/bin-prettier.js:6974:13)
    at normalize (/usr/local/lib/node_modules/prettier/bin-prettier.js:7065:19)
    at textToDoc (/usr/local/lib/node_modules/prettier/bin-prettier.js:9830:21)
    at /usr/local/lib/node_modules/prettier/bin-prettier.js:9824:14
    at formatBodyContent (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1675:22)
    at /Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:85
    at embedTag (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1697:15)
    at embedType (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:52)
    at embedScript (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1623:41)
    at Object.embed (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1632:20)
ConfigError: Couldn't resolve parser "babel-ts"
    at resolveParser$1 (/usr/local/lib/node_modules/prettier/bin-prettier.js:6974:13)
    at normalize (/usr/local/lib/node_modules/prettier/bin-prettier.js:7065:19)
    at textToDoc (/usr/local/lib/node_modules/prettier/bin-prettier.js:9830:21)
    at /usr/local/lib/node_modules/prettier/bin-prettier.js:9824:14
    at formatBodyContent (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1675:22)
    at /Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:85
    at embedTag (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1697:15)
    at embedType (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:52)
    at embedScript (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1623:41)
    at Object.embed (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1632:20)
ConfigError: Couldn't resolve parser "babel-ts"
    at resolveParser$1 (/usr/local/lib/node_modules/prettier/bin-prettier.js:6974:13)
    at normalize (/usr/local/lib/node_modules/prettier/bin-prettier.js:7065:19)
    at textToDoc (/usr/local/lib/node_modules/prettier/bin-prettier.js:9830:21)
    at /usr/local/lib/node_modules/prettier/bin-prettier.js:9824:14
    at formatBodyContent (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1675:22)
    at /Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:85
    at embedTag (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1697:15)
    at embedType (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:52)
    at embedScript (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1623:41)
    at Object.embed (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1632:20)
ConfigError: Couldn't resolve parser "babel-ts"
    at resolveParser$1 (/usr/local/lib/node_modules/prettier/bin-prettier.js:6974:13)
    at normalize (/usr/local/lib/node_modules/prettier/bin-prettier.js:7065:19)
    at textToDoc (/usr/local/lib/node_modules/prettier/bin-prettier.js:9830:21)
    at /usr/local/lib/node_modules/prettier/bin-prettier.js:9824:14
    at formatBodyContent (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1675:22)
    at /Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:85
    at embedTag (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1697:15)
    at embedType (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:52)
    at embedScript (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1623:41)
    at Object.embed (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1632:20)
ConfigError: Couldn't resolve parser "babel-ts"
    at resolveParser$1 (/usr/local/lib/node_modules/prettier/bin-prettier.js:6974:13)
    at normalize (/usr/local/lib/node_modules/prettier/bin-prettier.js:7065:19)
    at textToDoc (/usr/local/lib/node_modules/prettier/bin-prettier.js:9830:21)
    at /usr/local/lib/node_modules/prettier/bin-prettier.js:9824:14
    at formatBodyContent (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1675:22)
    at /Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:85
    at embedTag (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1697:15)
    at embedType (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1622:52)
    at embedScript (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1623:41)
    at Object.embed (/Users/johanronsse/.npm/_npx/34400/lib/node_modules/stackmix/node_modules/prettier-plugin-svelte/plugin.js:1632:20)```

**Comment by jakobrosenberg** [comment]
Never seen this error before. I personally try to avoid Babel at any cost 😅

Did you fix it and if so how?

**Comment by Wolfr** [comment]
It didn't cause any errors, it just logged a bunch of output. I see they are in my local install (`/usr/local`) so probably just a local mishap. Closing it...!
